### ISSUE TITLE
Connection Status LED

### ISSUE THREAD

**Issue by hadesto** [pr-holonet/pr-holonet#2]
Need to enable the pi to pull connection status from the rockblock and light up red/yellow/green status LED.This includes setting up the correct GPIO on pi and doing the hardware connection.

**Comment by ewanmellor** [comment]
Done.  The code assumes a shared cathode RGB LED is attached as pins 22, 24, 26 + ground at 25. 
 This will need to be wired with appropriate resistors in series to avoid drawing too much current from the Pi.

Blue = booting, Red = RockBLOCK broken, Yellow = No / low signal, Green = good signal.
