### ISSUE TITLE
Auto start PR-Holonet at bootup

### ISSUE THREAD

**Issue by hadesto** [pr-holonet/pr-holonet#24]
setup a process to start the server as soon as the system boots up

**Comment by ewanmellor** [comment]
I've already done this (unless I've forgotten something).  supervisord starts gunicorn, which runs holonet-web.  The config file for supervisord is in holonet-web/pr-holonet-web.conf.

**Comment by hadesto** [comment]
Roger that. Maybe I broke it and didn't realize. I'll take a look.

**Comment by hadesto** [comment]
Already included in production setup.

Thanks for the heads up @ewanmellor
