### ISSUE TITLE
Incoming messages

### ISSUE THREAD

**Issue by hadesto** [pr-holonet/pr-holonet#4]
need to build feature for routing incoming messages to correct device and properly thread messages. I think part of this is already on the web server portion. need to setup routing for twilio

**Comment by ewanmellor** [comment]
Done, more or less.

Messages leave my cell phone, go to Twilio, to Amazon Lambda, to Iridium.  All that is working great.  

At that point, the RockBLOCK is supposed to see a ring indicator.  The code for that is done, but I have never actually seen it work end to end.  I never seem to get Iridium signal for long enough for the ring notification to come through (or I've screwed something up of course).  More testing required.

Once we are able to check the Iridium network for new messages, the actual message fetch and display is all working.

Closing this ticket.  If we decide there's a bug with ring indicator handling then we can open a new one.
